// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUsrUser = "usr_users"

// UsrUser mapped from table <usr_users>
type UsrUser struct {
	ID        int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Username  string    `gorm:"column:username;type:varchar(36);comment:用户名" json:"username"`                      // 用户名
	Token     string    `gorm:"column:token;type:varchar(2048);not null;comment:github token （加密存储）" json:"token"` // github token （加密存储）
	Email     string    `gorm:"column:email;type:varchar(128);not null;comment:邮箱" json:"email"`                   // 邮箱
	AesKey    string    `gorm:"column:aes_key;type:varchar(2048);not null;comment:对称加密密钥" json:"aes_key"`          // 对称加密密钥
	GmtCreate time.Time `gorm:"column:gmt_create;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"gmt_create"`
	GmtUpdate time.Time `gorm:"column:gmt_update;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"gmt_update"`
}

// TableName UsrUser's table name
func (*UsrUser) TableName() string {
	return TableNameUsrUser
}
