app:
  env: "dev"
  name: "llm-code-review"
  host: "0.0.0.0:37229"
  log:
    path: "/Users/lyydsheep/workspace/Go/projects/llm_code_review/log/file.log"
    maxSize: 100
    maxAge: 60
  pagination:
    defaultSize: 20
    maxSize: 100
database:
  master:
    type: "mysql"
    dsn: "root:root@tcp(localhost:33060)/code_review?charset=utf8mb4&parseTime=True&loc=Local"
    maxOpen: 100
    maxIdle: 10
    maxLifeTime: 60
  slave:
    type: "mysql"
    dsn: "root:root@tcp(localhost:33060)/code_review?charset=utf8mb4&parseTime=True&loc=Local"
    maxOpen: 100
    maxIdle: 10
    maxLifeTime: 60
redis:
  addr: "your-redis-host:your-redis-port"
  password: "your-redis-password"
  poolSize: 10
  db: 0
kafka:
  brokers: [ "localhost:9092"]